### ISSUE TITLE
A new `resolveInclude` is added on each compilation

### ISSUE THREAD

**Issue by schuetzm** [sarscode/parcel-transformer-ejs#3]
The code overrides the global `ejs` object's `resolveInclude()` method, and calling the previously saved original one:
https://github.com/sarscode/parcel-transformer-ejs/blob/2f60371a4cfed754bffd24de85394a54d744ffb5/lib/index.js#L36-L40

This happens on each compilation, which leads to an evergrowing chain of methods being added. Instead, the `includer` option to `ejs.compile()` should be used:

```js
const includer = (originalPath, parsedPath) => {
    includes.push(parsedPath);
    return {
        filename: parsedPath,
    };
};
ejs.compile(source, {
    includes,
    ...
});
```

**Comment by sarscode** [comment]
Hello @schuetzm , thanks for submitting an issue. I will take a look at improving this by weekend. However, you can submit a PR if you have a more efficient solution.
