### ISSUE TITLE
Invalid fileName

### ISSUE THREAD

**Issue by believer** [sarscode/parcel-transformer-ejs#7]
After upgrading to `v1.0.0` I've started seeing an error `input.fileName.split is not a function`. This seems to be due to [this change](https://github.com/sarscode/parcel-transformer-ejs/blob/main/lib/index.js#L16) where `fileName` was changed from a string to an array.

**Comment by sarscode** [comment]
Hello @believer , `v1.0.0` works well as tested with the sample project in the `/example` directory in this repo. I have also tested it building a landing page - [http://github.com/sarscode/freelancer-landing-page](https://github.com/sarscode/freelancer-landing-page) see [live version](https://freelancer-landing-page.surge.sh/). Can you please share some snippet of your `package.json` file.

**Comment by believer** [comment]
That's what's weird, I can't see any differences in the setups. Here's the relevant part of the `package.json`:

```json
{
  "scripts": {
    "dev": "parcel styleguide/index.ejs -p 9999",
  },
  "devDependencies": {
    "@parcel/config-default": "2.6.2",
    "@parcel/transformer-sass": "2.6.2",
    "parcel": "2.6.2",
    "parcel-transformer-ejs": "1.0.0",
  }
}
```

`.parcelrc` is also basic:

```json
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "*.ejs": ["parcel-transformer-ejs"]
  }
}
```

**Comment by sarscode** [comment]
This is quite strange or could it be OS specific. Please revert to use [`parcel-transformer-ejs@0.2.1`](https://www.npmjs.com/package/parcel-transformer-ejs/v/0.2.1) while I try to find a solution to this. However, if you come up with a solution a PR is definitely welcomed.

**Comment by believer** [comment]
I'm using macOS if that helps in any way. Will definitely open a PR if I can find a solution.

**Comment by believer** [comment]
I've tracked it down to not having an `.ejsrc`. That makes the code take [this path](https://github.com/sarscode/parcel-transformer-ejs/blob/main/lib/index.js#L15) without `contents`.

`fileName` is supposed to be a string  for `invalidateOnFileCreate` according to [the type](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/types/index.js#L1474). This leads to the error because `split` doesn't exist on an array.

I'm not sure what's the best way to solve it. Do you have an idea?

**Comment by goosewobbler** [comment]
I had a go at fixing this.  
https://github.com/sarscode/parcel-transformer-ejs/pull/10

**Comment by sarscode** [comment]
@goosewobbler Thanks for your contribution. I have been procrastinating a fix.
